enum CharacterActionTypes {
  GET_CHARACTERS_START = 'GET_CHARACTERS_START',
  GET_CHARACTERS_SUCCESS = 'GET_CHARACTERS_SUCCESS',
  GET_CHARACTERS_FAILURE = 'GET_CHARACTERS_FAILURE'
}

export default CharacterActionTypes;