enum CharacterActionTypes {
  SET_CHARACTER           = 'SET_CHARACTER',
  SEARCH_CHARACTERS       = 'SEARCH_CHARACTERS',
  GET_CHARACTERS_START    = 'GET_CHARACTERS_START',
  GET_CHARACTERS_SUCCESS  = 'GET_CHARACTERS_SUCCESS',
  GET_CHARACTERS_FAILURE  = 'GET_CHARACTERS_FAILURE'
}

export default CharacterActionTypes;
